import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { Trash2 } from "lucide-react";
import { formatPrice } from "../../utils/formatPrice";
import { useApp } from "../../context/AppContext";
export const CartItem = ({ item }) => {
    const { updateCartQty, removeFromCart } = useApp();
    return (_jsxs("div", { className: "flex items-center gap-4 py-4 border-b border-gray-100 dark:border-gray-800 last:border-b-0", children: [_jsx("div", { className: "w-20 h-20 rounded-2xl bg-gray-50 dark:bg-gray-800/60 p-2 flex items-center justify-center shrink-0 border border-gray-100 dark:border-gray-800", children: _jsx("img", { src: item.product.images[0], alt: item.product.name, className: "max-h-full max-w-full object-contain" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h4", { className: "text-sm font-bold text-gray-900 dark:text-white truncate", children: item.product.name }), _jsxs("div", { className: "flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400 mt-1", children: [item.selectedColor && _jsxs("span", { children: ["Color: ", item.selectedColor] }), item.selectedColor && item.selectedSize && _jsx("span", { children: "\u2022" }), item.selectedSize && _jsxs("span", { children: ["Size: ", item.selectedSize] })] }), _jsx("div", { className: "text-sm font-extrabold text-[#4F6EF7] mt-1", children: formatPrice(item.product.price) })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("div", { className: "flex items-center border border-gray-200 dark:border-gray-700 rounded-xl p-0.5 bg-gray-50 dark:bg-gray-800/60", children: [_jsx("button", { type: "button", onClick: () => updateCartQty(item.product.id, item.quantity - 1), className: "w-7 h-7 flex items-center justify-center text-xs font-bold text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-gray-700 rounded-lg transition-colors", children: "-" }), _jsx("span", { className: "w-8 text-center text-xs font-bold text-gray-900 dark:text-white", children: item.quantity }), _jsx("button", { type: "button", onClick: () => updateCartQty(item.product.id, item.quantity + 1), className: "w-7 h-7 flex items-center justify-center text-xs font-bold text-gray-600 dark:text-gray-300 hover:bg-white dark:hover:bg-gray-700 rounded-lg transition-colors", children: "+" })] }), _jsx("button", { type: "button", onClick: () => removeFromCart(item.product.id), className: "p-2 text-gray-400 hover:text-red-500 transition-colors", title: "Remove item", children: _jsx(Trash2, { className: "w-4 h-4" }) })] })] }));
};
