import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { formatPrice } from "../../utils/formatPrice";
import { Button } from "../common/Button";
export const CartSummary = ({ subtotal, discount = 0, shipping = 0, tax = 0, total, onCheckout, showCheckoutButton = true, }) => {
    return (_jsxs("div", { className: "p-6 rounded-3xl bg-white dark:bg-[#151824] border border-gray-100 dark:border-gray-800 shadow-xs space-y-4", children: [_jsx("h3", { className: "text-base font-extrabold text-gray-900 dark:text-white", children: "Order Summary" }), _jsxs("div", { className: "space-y-3 text-sm", children: [_jsxs("div", { className: "flex justify-between text-gray-600 dark:text-gray-400", children: [_jsx("span", { children: "Subtotal" }), _jsx("span", { className: "font-semibold text-gray-900 dark:text-white", children: formatPrice(subtotal) })] }), discount > 0 && (_jsxs("div", { className: "flex justify-between text-emerald-600 dark:text-emerald-400", children: [_jsx("span", { children: "Discount" }), _jsxs("span", { className: "font-semibold", children: ["-", formatPrice(discount)] })] })), _jsxs("div", { className: "flex justify-between text-gray-600 dark:text-gray-400", children: [_jsx("span", { children: "Shipping" }), _jsx("span", { className: "font-semibold text-gray-900 dark:text-white", children: shipping === 0 ? "FREE" : formatPrice(shipping) })] }), tax > 0 && (_jsxs("div", { className: "flex justify-between text-gray-600 dark:text-gray-400", children: [_jsx("span", { children: "Estimated Tax" }), _jsx("span", { className: "font-semibold text-gray-900 dark:text-white", children: formatPrice(tax) })] })), _jsxs("div", { className: "pt-3 border-t border-gray-100 dark:border-gray-800 flex justify-between text-base font-black text-gray-900 dark:text-white", children: [_jsx("span", { children: "Total" }), _jsx("span", { className: "text-[#4F6EF7]", children: formatPrice(total) })] })] }), showCheckoutButton && (_jsx("div", { className: "pt-2", children: onCheckout ? (_jsx(Button, { onClick: onCheckout, size: "lg", className: "w-full py-3.5", rightIcon: _jsx(ArrowRight, { className: "w-4 h-4" }), children: "Proceed to Checkout" })) : (_jsx(Link, { to: "/checkout", className: "block w-full", children: _jsx(Button, { size: "lg", className: "w-full py-3.5", rightIcon: _jsx(ArrowRight, { className: "w-4 h-4" }), children: "Proceed to Checkout" }) })) })), _jsxs("div", { className: "flex items-center justify-center gap-2 pt-2 text-xs text-gray-400", children: [_jsx(ShieldCheck, { className: "w-4 h-4 text-emerald-500" }), _jsx("span", { children: "Secure 256-Bit SSL Checkout" })] })] }));
};
