import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { Heart, Star, ShoppingBag, CheckCircle2 } from "lucide-react";
import { formatPrice } from "../../utils/formatPrice";
import { useApp } from "../../context/AppContext";
export const ProductCardList = ({ product }) => {
    const { toggleWishlist, isInWishlist, addToCart, setSelectedProduct } = useApp();
    const isWishlisted = isInWishlist(product.id);
    const reviewFormatted = product.numReviews >= 1000
        ? `${(product.numReviews / 1000).toFixed(1)}k`
        : product.numReviews.toString();
    return (_jsxs("div", { className: "group relative bg-white dark:bg-[#161828] rounded-[22px] p-4 border border-gray-100 dark:border-gray-800 shadow-xs hover:shadow-xl transition-all duration-300 flex flex-col sm:flex-row items-center gap-4 sm:gap-6", children: [_jsxs("div", { className: "relative w-full sm:w-44 h-44 shrink-0 bg-gray-50 dark:bg-[#1C1E32] rounded-2xl flex items-center justify-center p-3 overflow-hidden cursor-pointer", onClick: () => setSelectedProduct(product), children: [_jsx("img", { src: product.images[0], alt: product.name, className: "max-h-full max-w-full object-contain transition-transform duration-300 group-hover:scale-105", loading: "lazy" }), product.discountPercentage > 0 && (_jsxs("span", { className: "absolute top-2.5 left-2.5 px-2 py-0.5 text-[10px] font-bold tracking-wide rounded-md bg-[#E6F4EA] dark:bg-[#143322] text-[#137333] dark:text-[#34D399]", children: [product.discountPercentage, "% OFF"] })), _jsx("button", { onClick: (e) => {
                            e.stopPropagation();
                            toggleWishlist(product.id);
                        }, className: "absolute top-2.5 right-2.5 w-7 h-7 rounded-full bg-white/90 dark:bg-gray-800/90 hover:bg-pink-50 dark:hover:bg-pink-950/40 flex items-center justify-center shadow-xs transition-colors cursor-pointer", title: isWishlisted ? "Remove from Wishlist" : "Add to Wishlist", children: _jsx(Heart, { className: `w-3.5 h-3.5 transition-transform duration-200 active:scale-125 ${isWishlisted
                                ? "fill-[#EC4899] text-[#EC4899]"
                                : "text-gray-400 hover:text-[#EC4899]"}` }) })] }), _jsxs("div", { className: "flex-1 min-w-0 space-y-2 py-1 w-full", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-[11px] font-bold uppercase tracking-wider text-[#4F6EF7]", children: product.brand }), _jsx("span", { className: "text-gray-300 dark:text-gray-700", children: "\u2022" }), _jsx("span", { className: "text-xs text-gray-500 dark:text-gray-400 capitalize", children: product.category })] }), _jsx("h3", { onClick: () => setSelectedProduct(product), className: "text-base font-bold text-gray-900 dark:text-gray-100 hover:text-[#4F6EF7] dark:hover:text-[#818CF8] cursor-pointer transition-colors", children: product.name }), _jsx("p", { className: "text-xs text-gray-500 dark:text-gray-400 line-clamp-2 leading-relaxed", children: product.description }), _jsxs("div", { className: "flex items-center gap-3 pt-1", children: [_jsxs("div", { className: "flex items-center gap-1 text-xs", children: [_jsx(Star, { className: "w-3.5 h-3.5 fill-[#FBBF24] text-[#FBBF24]" }), _jsx("span", { className: "font-bold text-gray-800 dark:text-gray-200", children: product.rating }), _jsxs("span", { className: "text-gray-400", children: ["(", reviewFormatted, " reviews)"] })] }), _jsxs("div", { className: "flex items-center gap-1 text-[11px] font-medium text-emerald-600 dark:text-emerald-400", children: [_jsx(CheckCircle2, { className: "w-3.5 h-3.5" }), _jsx("span", { children: product.stock > 0 ? "In Stock" : "Out of Stock" })] })] })] }), _jsxs("div", { className: "flex sm:flex-col items-center sm:items-end justify-between sm:justify-center gap-3 w-full sm:w-44 pt-3 sm:pt-0 border-t sm:border-t-0 border-gray-100 dark:border-gray-800 shrink-0", children: [_jsxs("div", { className: "sm:text-right", children: [_jsx("div", { className: "text-lg font-black text-gray-900 dark:text-white", children: formatPrice(product.discountPrice) }), product.price > product.discountPrice && (_jsx("span", { className: "text-xs text-gray-400 line-through block", children: formatPrice(product.price) }))] }), _jsxs("button", { onClick: () => addToCart(product), className: "px-4 py-2 bg-[#4F6EF7] hover:bg-[#3B5BDB] text-white text-xs font-bold rounded-xl shadow-xs flex items-center gap-1.5 transition-all hover:scale-105 active:scale-95 cursor-pointer", children: [_jsx(ShoppingBag, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "Add to Cart" })] })] })] }));
};
