import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { Heart, Star, ShoppingBag } from "lucide-react";
import { formatPrice } from "../../utils/formatPrice";
import { useApp } from "../../context/AppContext";
export const ProductCard = ({ product }) => {
    const { toggleWishlist, isInWishlist, addToCart, setSelectedProduct } = useApp();
    const isWishlisted = isInWishlist(product.id);
    const reviewFormatted = product.numReviews >= 1000
        ? `${(product.numReviews / 1000).toFixed(1)}k`
        : product.numReviews.toString();
    return (_jsxs("div", { className: "group relative bg-white dark:bg-[#161828] rounded-2xl sm:rounded-[22px] p-3 sm:p-4 border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1 flex flex-col justify-between w-full min-w-0", children: [_jsxs("div", { className: "flex items-center justify-between w-full relative z-10", children: [product.discountPercentage > 0 ? (_jsxs("span", { className: "px-2 py-0.5 sm:px-2.5 sm:py-1 text-[10px] sm:text-[11px] font-bold tracking-wide rounded-md sm:rounded-lg bg-[#E6F4EA] dark:bg-[#143322] text-[#137333] dark:text-[#34D399]", children: [product.discountPercentage, "% OFF"] })) : (_jsx("span", {})), _jsx("button", { onClick: (e) => {
                            e.stopPropagation();
                            toggleWishlist(product.id);
                        }, className: "w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-gray-50/80 dark:bg-gray-800/80 hover:bg-pink-50 dark:hover:bg-pink-950/40 flex items-center justify-center transition-colors cursor-pointer", title: isWishlisted ? "Remove from Wishlist" : "Add to Wishlist", children: _jsx(Heart, { className: `w-3.5 h-3.5 sm:w-4 sm:h-4 transition-transform duration-200 active:scale-125 ${isWishlisted
                                ? "fill-[#EC4899] text-[#EC4899]"
                                : "text-gray-400 hover:text-[#EC4899]"}` }) })] }), _jsx("div", { onClick: () => setSelectedProduct(product), className: "relative my-2 sm:my-3 h-32 sm:h-44 md:h-48 w-full flex items-center justify-center overflow-hidden cursor-pointer", children: _jsx("img", { src: product.images[0], alt: product.name, className: "max-h-full max-w-full object-contain transition-transform duration-300 group-hover:scale-105", loading: "lazy" }) }), _jsxs("div", { className: "space-y-1 sm:space-y-1.5 pt-1", children: [_jsx("h3", { onClick: () => setSelectedProduct(product), className: "text-xs sm:text-sm font-bold text-gray-900 dark:text-gray-100 hover:text-[#4F6EF7] dark:hover:text-[#818CF8] truncate cursor-pointer transition-colors", title: product.name, children: product.name }), _jsxs("div", { className: "flex flex-wrap items-baseline gap-1 sm:gap-2", children: [_jsx("span", { className: "text-sm sm:text-base font-extrabold text-gray-900 dark:text-white", children: formatPrice(product.discountPrice) }), product.price > product.discountPrice && (_jsx("span", { className: "text-[10px] sm:text-xs text-gray-400 line-through", children: formatPrice(product.price) }))] }), _jsxs("div", { className: "flex items-center justify-between pt-1", children: [_jsxs("div", { className: "flex items-center gap-1 text-[11px] sm:text-xs", children: [_jsx(Star, { className: "w-3 h-3 sm:w-3.5 sm:h-3.5 fill-[#FBBF24] text-[#FBBF24]" }), _jsx("span", { className: "font-bold text-gray-800 dark:text-gray-200", children: product.rating }), _jsxs("span", { className: "text-gray-400", children: ["(", reviewFormatted, ")"] })] }), _jsx("button", { onClick: () => addToCart(product), className: "w-7 h-7 sm:w-8 sm:h-8 rounded-full bg-gray-100 dark:bg-gray-800 hover:bg-[#4F6EF7] hover:text-white text-gray-700 dark:text-gray-200 flex items-center justify-center transition-all hover:scale-110 active:scale-95 cursor-pointer", title: "Add to cart", children: _jsx(ShoppingBag, { className: "w-3.5 h-3.5" }) })] })] })] }));
};
